# Use the official Ruby image
FROM ruby:latest

# Set the working directory inside the container
WORKDIR /usr/src/app

# Set the default command to run the Ruby script
CMD ["ruby", "./auth_service.rb"]
