services:
  ruby-service:
    build:
      context: ./srcs/auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    volumes:
      - ./srcs/auth_service:/usr/src/app
    networks:
      - transcendence

  proxy-service:
    build:
      context: ./srcs/proxy_service
      dockerfile: Dockerfile
    container_name: proxy_service
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./srcs/proxy_service/static:/static
    networks:
      - transcendence

  db-service:
    build:
      context: ./srcs/db_service
      dockerfile: Dockerfile
    container_name: db_service
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: auth_db
    volumes:
      - ./srcs/db_service/init:/docker-entrypoint-initdb.d
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge
