# frozen_string_literal: true

# Gemfile
source 'https://rubygems.org'
gem 'bcrypt'
gem 'json'
gem 'jwt'
gem 'pg'
gem 'puma'
gem 'rackup'
gem 'rubocop', group: 'development', require: false
gem 'sequel'
gem 'sinatra'
gem 'vault'