# Gemfile
source 'https://rubygems.org'

gem 'bcrypt'
gem 'json'
gem 'jwt'
gem 'pg'
gem 'puma'
gem 'rackup'
gem 'rubocop', group: 'development', require: false
gem 'sequel'
gem 'sinatra'

# Debugging gems
gem 'ruby-debug-ide'
gem 'debase'