# Gemfile
source 'https://rubygems.org'

gem 'json'
gem 'jwt'
gem 'rackup'
gem 'rubocop', group: 'development', require: false
gem 'sinatra-websocket'
gem 'sinatra'
gem 'thin'
gem 'ostruct'
gem 'logger'
#development
gem 'rerun'