services:
  ruby-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    volumes:
      - ./auth_service:/usr/src/app
    networks:
      - transcendence

  proxy-service:
    build:
      context: ./proxy_service
      dockerfile: Dockerfile
    container_name: proxy_service
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy_service/static:/var/www/proxy_service/static
      - ../frontend:/var/www/proxy_service/frontend
    networks:
      - transcendence

  db-service:
    build:
      context: ./db_service
      dockerfile: Dockerfile
    container_name: db_service
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: auth_db
    volumes:
      - ./db_service/init:/docker-entrypoint-initdb.d
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge
